<a href="https://colab.research.google.com/github/vibeshvidya/Advanced-AI-ML/blob/main/27_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Libraries

In [ ]:
import numpy as np
import pandas as pd

# Encoding.
from sklearn.preprocessing import LabelEncoder
# splitting data into train and test data
from sklearn.model_selection import train_test_split

# classification algorithms
from sklearn.linear_model import LogisticRegression # logistic regression
from sklearn.neighbors import KNeighborsClassifier  # KNN
from sklearn.svm import SVC                         # SVM
from sklearn.tree import DecisionTreeClassifier     # Decision Tree

# evaluation libraries
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Reading the dataset

In [ ]:
filepath = '/content/drive/MyDrive/ICT_Online/AI ML/IIT Palakkad Advanced AI/Data/iris.csv'
df_iris = pd.read_csv(filepath)
df_iris.head(2)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [ ]:
df_iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

# Pre processing.

In [ ]:
# before encoding,
df_iris['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
# Iris dataset is already pre processed.
# Except target column Encoding.

# since it is target column, we use label encoding
label_encode = LabelEncoder()
df_iris['species'] = label_encode.fit_transform(
                                  df_iris['species']
                                                  )
df_iris.head(2)

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0

In [ ]:
# after encoding,
df_iris['species'].unique()

array([0, 1, 2])

In [ ]:
# verify all the data in the dataFrame are numerical
# this needs to be done before ML model building.

# ML model building.

## Data splitting

In [ ]:
# % of data split among train and test data
# train 70 - 80
# test 30 - 20

# Split dataset in to target and features

y = df_iris['species']                  # target
X = df_iris.drop(['species'], axis =1)  # features

In [ ]:
y.head(2)

0    0
1    0
Name: species, dtype: int64

In [ ]:
X.head(2)

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2

In [ ]:
# split into train and test datasets.
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 12)

In [ ]:
X_train.head()

     sepal_length  sepal_width  petal_length  petal_width
17            5.1          3.5           1.4          0.3
81            5.5          2.4           3.7          1.0
103           6.3          2.9           5.6          1.8
33            5.5          4.2           1.4          0.2
101           5.8          2.7           5.1          1.9

In [ ]:
X_test.head()

     sepal_length  sepal_width  petal_length  petal_width
40            5.0          3.5           1.3          0.3
146           6.3          2.5           5.0          1.9
38            4.4          3.0           1.3          0.2
99            5.7          2.8           4.1          1.3
143           6.8          3.2           5.9          2.3

In [ ]:
y_train.head()

17     0
81     1
103    2
33     0
101    2
Name: species, dtype: int64

In [ ]:
y_test.head()

40     0
146    2
38     0
99     1
143    2
Name: species, dtype: int64

## ML models

### Logistic Regression

In [ ]:
# initialize your model
log_model = LogisticRegression()
# train your model
log_model.fit(X_train, y_train)
# make predictions using the model
y_pred_log = log_model.predict(X_test)
# evaluate your model by comparing it's prediction with test values
acc_log = accuracy_score(y_pred_log, y_test)
prec_log = precision_score(y_pred_log, y_test,
                           average = 'weighted')
recall_log = recall_score(y_pred_log, y_test,
                          average = 'weighted')
f1_log = f1_score(y_pred_log, y_test,
                  average = 'weighted')
conf_matrix_log = confusion_matrix(y_pred_log, y_test)

print('Accuracy of the model : ', acc_log)
print('Precision of the model : ', prec_log)
print('Recall of the model : ', recall_log)
print('f1 score of the model : ', f1_log)
print('confusion matrix of the model : ', conf_matrix_log)

Accuracy of the model :  0.9666666666666667
Precision of the model :  0.9703703703703703
Recall of the model :  0.9666666666666667
f1 score of the model :  0.9667698658410733
confusion matrix of the model :  [[12  0  0]
 [ 0  8  0]
 [ 0  1  9]]

### k-NN
k Nearest Neighbours

In [ ]:
# assume k = 3
# initialize your model
knn_model = KNeighborsClassifier(n_neighbors=3)
# train your model
knn_model.fit(X_train, y_train)
# make predictions using the model
y_pred_knn = knn_model.predict(X_test)
# evaluate your model by comparing it's prediction with test values
acc_knn = accuracy_score(y_pred_knn, y_test)

print('Accuracy of the model : ', acc_knn)

Accuracy of the model :  0.9666666666666667

### SVM classification

In [ ]:
# SVM classifier
# initi
svc_model = SVC()
# train the model

### Naive Bayes

In [ ]:
# Naive Bayes

### Decision Tree

In [ ]:
# Decision tree

# initialize your model
knn_model = KNeighborsClassifier(n_neighbors=3)
# train your model
knn_model.fit(X_train, y_train)
# make predictions using the model
y_pred_knn = knn_model.predict(X_test)
# evaluate your model by comparing it's prediction with test values
acc_knn = accuracy_score(y_pred_knn, y_test)

print('Accuracy of the model : ', acc_knn)

In [ ]:
# Random forest

In [ ]:
# XG boost

##